### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by chqaqc** [feiyunzhang/video-copy-detection-for-compact-cnn-based-representation#1]
Do you have the complete source code of this article to share? Thank you very much。

**Comment by feiyunzhang** [comment]
sorry, i don't have because of the long time, you can complete it step by step follow the paper

**Comment by feiyunzhang** [comment]
> Do you have the complete source code of this article to share? Thank you very much。

but in my memory, it is a long time for training ksvd, this methods maybe not suit for search。

**Comment by chqaqc** [comment]
thanks a lot
